//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://localhost/Pleiades/Service1.svc";
    }
    
    /// <remarks/>
    public event GetDataCompletedEventHandler GetDataCompleted;
    
    /// <remarks/>
    public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aleksjones.com/IService1/GetData", RequestNamespace="http://aleksjones.com", ResponseNamespace="http://aleksjones.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
        object[] results = this.Invoke("GetData", new object[] {
                    value,
                    valueSpecified});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetData(int value, bool valueSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetData", new object[] {
                    value,
                    valueSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetDataAsync(int value, bool valueSpecified) {
        this.GetDataAsync(value, valueSpecified, null);
    }
    
    /// <remarks/>
    public void GetDataAsync(int value, bool valueSpecified, object userState) {
        if ((this.GetDataOperationCompleted == null)) {
            this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
        }
        this.InvokeAsync("GetData", new object[] {
                    value,
                    valueSpecified}, this.GetDataOperationCompleted, userState);
    }
    
    private void OnGetDataOperationCompleted(object arg) {
        if ((this.GetDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aleksjones.com/IService1/GetDataUsingDataContract", RequestNamespace="http://aleksjones.com", ResponseNamespace="http://aleksjones.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
        object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                    composite});
        return ((CompositeType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDataUsingDataContract(CompositeType composite, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDataUsingDataContract", new object[] {
                    composite}, callback, asyncState);
    }
    
    /// <remarks/>
    public CompositeType EndGetDataUsingDataContract(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CompositeType)(results[0]));
    }
    
    /// <remarks/>
    public void GetDataUsingDataContractAsync(CompositeType composite) {
        this.GetDataUsingDataContractAsync(composite, null);
    }
    
    /// <remarks/>
    public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
        if ((this.GetDataUsingDataContractOperationCompleted == null)) {
            this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
        }
        this.InvokeAsync("GetDataUsingDataContract", new object[] {
                    composite}, this.GetDataUsingDataContractOperationCompleted, userState);
    }
    
    private void OnGetDataUsingDataContractOperationCompleted(object arg) {
        if ((this.GetDataUsingDataContractCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aleksjones.com")]
public partial class CompositeType {
    
    private bool boolValueField;
    
    private bool boolValueFieldSpecified;
    
    private string stringValueField;
    
    /// <remarks/>
    public bool BoolValue {
        get {
            return this.boolValueField;
        }
        set {
            this.boolValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BoolValueSpecified {
        get {
            return this.boolValueFieldSpecified;
        }
        set {
            this.boolValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string StringValue {
        get {
            return this.stringValueField;
        }
        set {
            this.stringValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CompositeType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CompositeType)(this.results[0]));
        }
    }
}
