//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pleiades.IntegrationTests.ServiceApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://aleksjones.com")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aleksjones.com", ConfigurationName="ServiceApp.IService1Enhanced")]
    public interface IService1Enhanced {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aleksjones.com/IService1/GetData", ReplyAction="http://aleksjones.com/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aleksjones.com/IService1/GetDataUsingDataContract", ReplyAction="http://aleksjones.com/IService1/GetDataUsingDataContractResponse")]
        Pleiades.IntegrationTests.ServiceApp.CompositeType GetDataUsingDataContract(Pleiades.IntegrationTests.ServiceApp.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aleksjones.com/IService1Enhanced/GetSpecial", ReplyAction="http://aleksjones.com/IService1Enhanced/GetSpecialResponse")]
        string GetSpecial(double value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1EnhancedChannel : Pleiades.IntegrationTests.ServiceApp.IService1Enhanced, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1EnhancedClient : System.ServiceModel.ClientBase<Pleiades.IntegrationTests.ServiceApp.IService1Enhanced>, Pleiades.IntegrationTests.ServiceApp.IService1Enhanced {
        
        public Service1EnhancedClient() {
        }
        
        public Service1EnhancedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1EnhancedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1EnhancedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1EnhancedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Pleiades.IntegrationTests.ServiceApp.CompositeType GetDataUsingDataContract(Pleiades.IntegrationTests.ServiceApp.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string GetSpecial(double value) {
            return base.Channel.GetSpecial(value);
        }
    }
}
